title: Fortran Toolkit

email: bpetit@cunef.edu

github_username:  borjapetit

navbar-links:
  Author's home: "https://deanattali.com"

navbar-col: "#EAEAEA"

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default
